---

name: tagme
author: norwd
description: "GitHub Action to manage tags"

branding:
  icon: tag
  color: blue

inputs:
  token:
    description: "Used to authenticate with GitHub, this should be a PAT with `repo: write` permissions."

  username:
    description: "Who the tag should be attributed to, defaults to the GitHub Actions bot."

  email:
    description: "Who the tag should be attributed to, defaults to the GitHub Actions bot."

  tag:
    required: true
    description: "The tag to create or update, e.g. `v1.2.3`."

  message:
    description: "An optional message to annotate the tag with."

  ref:
    description: "Which git object to tag, defaults to `GITHUB_REF`."

runs:
  using: "composite"
  steps:
    - name: "Validate Config"
      env:
        PAT: ${{ inputs.token || github.token }}
        USR: ${{ inputs.username || 'github-actions[bot]' }}
        EML: ${{ inputs.email || '41898282+github-actions[bot]@users.noreply.github.com' }}
        TAG: ${{ inputs.tag }}
        MSG: ${{ inputs.message || 'inputs.tag' }}
        REF: ${{ inputs.ref || github.ref }}
      shell: bash
      run: |
        if [ -z "${PAT}" ]
        then
          echo "::error::No token provided!"
          exit 1
        fi

        if [ -z "${USR}" ]
        then
          echo "::error::No username provided"
          exit 1
        fi

        if [ -z "${EML}" ]
        then
          echo "::error::No email provided"
          exit 1
        fi

        if [ -z "${TAG}" ]
        then
          echo "::error::No tag name provided"
          exit 1
        fi

        if [ -z "${MSG}" ]
        then
          echo "::error::No tag message provided"
          exit 1
        fi

        if [ -z "${REF}" ]
        then
          echo "::error::No commit to tag specified"
          exit 1
        fi

        echo "TOKEN=${PATH}" >> "${GITHUB_ENV}"
        echo "REQUEST<<EOF" >> "${GITHUB_ENV}"
        cat << EOF | tee -a "${GITHUB_ENV}"
        {
          "tag": "${TAG}",
          "message": "${MSG}",
          "object": "${REF}",
          "type": "commit",
          "tagger": {
            "name": "${USR}",
            "email": "${EML}",
            "date": "$(date +"%Y-%m-%dT%H:%M:%S%z")"
          }
        }
        EOF
        echo "EOF" >> "${GITHUB_ENV}"

    - name: "Create Tag"
      shell: bash
      run: |
        curl https://api.github.com/repos/${{ github.repository }}/git/tags \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${TOKEN}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -d "${REQUEST}"
