---

name: tagme
author: norwd
description: "GitHub Action to manage tags"

branding:
  icon: tag
  color: blue

inputs:
  token:
    description: "Used to authenticate with GitHub, this should be a PAT with `repo: write` permissions."

  username:
    default: "github-actions[bot]"
    description: "Who the tag should be attributed to, defaults to the GitHub Actions bot."

  email:
    default: "41898282+github-actions[bot]@users.noreply.github.com"
    description: "Who the tag should be attributed to, defaults to the GitHub Actions bot."

  tag:
    required: true
    description: "The tag to create or update, e.g. `v1.2.3`."

  message:
    description: "An optional message to annotate the tag with."

  ref:
    description: "Which git object to tag, defaults to `GITHUB_REF`."

runs:
  using: "composite"
  steps:
    - name: "<TODO>"
      run: |
        echo <TODO>
