---

name: tagme
author: norwd
description: "GitHub Action to manage tags"

branding:
  icon: tag
  color: blue

inputs:
  token:
    description: "Used to authenticate with GitHub, this should be a PAT with `repo: write` permissions."

  username:
    default: "github-actions[bot]"
    description: "Who the tag should be attributed to, defaults to the GitHub Actions bot."

  email:
    default: "41898282+github-actions[bot]@users.noreply.github.com"
    description: "Who the tag should be attributed to, defaults to the GitHub Actions bot."

  tag:
    required: true
    description: "The tag to create or update, e.g. `v1.2.3`."

  message:
    description: "An optional message to annotate the tag with."

  ref:
    description: "Which git object to tag, defaults to `GITHUB_REF`."

runs:
  using: "composite"
  steps:
    - name: "Create Tag"
      env:
        TOKEN: ${{ inputs.token }}
        USERNAME: ${{ inputs.username }}
        EMAIL: ${{ inputs.email }}
        TAG: ${{ inputs.tag }}
        REF: ${{ inputs.ref }}
      run: |
        curl \
          https://api.github.com/repos/${{ github.repository }}/git/tags \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${TOKEN}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -d '{ \
            "tag": "${TAG}", \
            "message": "initial version", \
            "object": "${REF}", \
            "type": "commit", \
            "tagger": { \
              "name": "${USERNAME}", \
              "email": "${EMAIL}", \
              "date": "$(date +"%Y-%m-%dT%H:%M:%S%z")" \
            } \
          }'
