---

name: ghtag
author: norwd
description: "GitHub Action to manage tags"

branding:
  icon: tag
  color: blue

inputs:
  token:
    description: "Used to authenticate with GitHub, this should be a PAT with `repo: write` permissions."

  username:
    description: "Who the tag should be attributed to, defaults to the GitHub Actions bot."

  email:
    description: "Who the tag should be attributed to, defaults to the GitHub Actions bot."

  tag:
    required: true
    description: "The tag to create or update, e.g. `v1.2.3`."

  message:
    description: "An optional message to annotate the tag with."

  ref:
    description: "Which git object to tag, defaults to `GITHUB_REF`."

runs:
  using: "composite"
  steps:
    - name: "Create Tag Object"
      env:
        GH_TOKEN: ${{ inputs.token || github.token }}
        USERNAME: ${{ inputs.username || 'github-actions[bot]' }}
        USERMAIL: ${{ inputs.email || '41898282+github-actions[bot]@users.noreply.github.com' }}
        TAG_NAME: ${{ inputs.tag }}
        TAG_MESG: ${{ inputs.message || inputs.tag }}
        TAG_HASH: ${{ inputs.ref || github.sha }}
      shell: bash
      run: |
        gh api repos/${{ github.repository }}/git/tags -X POST --input - << EOF
        {
          "tag": "${TAG_NAME}",
          "message": "${TAG_MESG}",
          "object": "${TAG_HASH}",
          "type": "commit",
          "tagger": {
            "name": "${USERNAME}",
            "email": "${USERMAIL}",
            "date": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
          }
        }
        EOF

    - name: "Create Tag Reference"
      env:
        GH_TOKEN: ${{ inputs.token || github.token }}
        TAG_NAME: ${{ inputs.tag }}
        TAG_HASH: ${{ inputs.ref || github.sha }}
      shell: bash
      run: |
        gh api repos/${{ github.repository }}/git/refs -X POST --input - << EOF
        {
          "ref": "refs/tags/${TAG_NAME}",
          "sha": "${TAG_HASH}"
        }
        EOF
