---

name: tagme
author: norwd
description: "GitHub Action to manage tags"

branding:
  icon: tag
  color: blue

inputs:
  token:
    description: "Used to authenticate with GitHub, this should be a PAT with `repo: write` permissions."

  username:
    default: "github-actions[bot]"
    description: "Who the tag should be attributed to, defaults to the GitHub Actions bot."

  email:
    default: "41898282+github-actions[bot]@users.noreply.github.com"
    description: "Who the tag should be attributed to, defaults to the GitHub Actions bot."

  tag:
    description: "<TODO>"

  message:
    description: "<TODO>"

  ref:
    description: "<TODO>"

runs:
  using: "composite"
  steps:
    - name: "<TODO>"
      run: |
        echo <TODO>
