---

name: "Create Release"
run-name: "Create Release `${{ inputs.tag }}`"
permissions: {}

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: "The tag to create."

defaults:
  run:
    shell: bash

jobs:
  tag:
    name: "Tag ${{ inputs.tag }}"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "Tag ${{ inputs.tag }} at ${{ github.ref }}"
        uses: norwd/tagme@5ce56a69d3d650d1e768fbe828774fb0853ae005
        with:
          tag: ${{ inputs.tag }}
